// Auto-generated from the existing florinsta index.html PRODUCTS array — exact names/prices/descriptions preserved.
export const SEED_PRODUCTS = [
  {
    legacyId: 9,
    name: "The Florinsta Harmony",
    slug: "the-florinsta-harmony",
    categorySlug: "bouquets",
    description: "Captures the playful yet sophisticated mix of textures and colors.",
    priceMinor: 29500,
    sku: "FLR-0009",
    mainImage: "/assets/img/x9.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 10,
    name: "The Dreamscape Bloom",
    slug: "the-dreamscape-bloom",
    categorySlug: "bouquets",
    description: "Reflects the ethereal, soft-focus quality of the color combination.",
    priceMinor: 67500,
    sku: "FLR-0010",
    mainImage: "/assets/img/x10.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 11,
    name: "Pastel Serenity",
    slug: "pastel-serenity",
    categorySlug: "bouquets",
    description: "Highlights the calm and gentle aesthetic of the arrangement.",
    priceMinor: 67500,
    sku: "FLR-0011",
    mainImage: "/assets/img/x11.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 12,
    name: "The Florinsta Whimsy",
    slug: "the-florinsta-whimsy",
    categorySlug: "bouquets",
    description: "Captures the playful yet sophisticated mix of textures and colors.",
    priceMinor: 67500,
    sku: "FLR-0012",
    mainImage: "/assets/img/x12.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 13,
    name: "Blossom Harmony",
    slug: "blossom-harmony",
    categorySlug: "bouquets",
    description: "Emphasizes the balanced blend of floral elements.",
    priceMinor: 47500,
    sku: "FLR-0013",
    mainImage: "/assets/img/x13.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 14,
    name: "Azure Blush",
    slug: "azure-blush",
    categorySlug: "bouquets",
    description: "Directly references the interplay between the blue hydrangea and pink floral elements.",
    priceMinor: 67500,
    sku: "FLR-0014",
    mainImage: "/assets/img/x14.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 15,
    name: "Dusk to Dawn",
    slug: "dusk-to-dawn",
    categorySlug: "bouquets",
    description: "A poetic name representing the beautiful flow of colors from dark to light.",
    priceMinor: 67500,
    sku: "FLR-0015",
    mainImage: "/assets/img/x15.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 16,
    name: "The Pearl Radiance",
    slug: "the-pearl-radiance",
    categorySlug: "bouquets",
    description: "Highlights the elegant pearl accents integrated into the white floral arrangement.",
    priceMinor: 47500,
    sku: "FLR-0016",
    mainImage: "/assets/img/x16.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 17,
    name: "Golden Radiance",
    slug: "golden-radiance",
    categorySlug: "bouquets",
    description: "Reflects the warm, uplifting yellow tones of the bouquet.",
    priceMinor: 37500,
    sku: "FLR-0017",
    mainImage: "/assets/img/x17.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 18,
    name: "Morning Meadow",
    slug: "morning-meadow",
    categorySlug: "bouquets",
    description: "Evokes the fresh, natural feel of this combination.",
    priceMinor: 37500,
    sku: "FLR-0018",
    mainImage: "/assets/img/x18.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 19,
    name: "Lavender Mist",
    slug: "lavender-mist",
    categorySlug: "bouquets",
    description: "Reflects the soft, ethereal blend of purple and white tones.",
    priceMinor: 57500,
    sku: "FLR-0019",
    mainImage: "/assets/img/x19.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 20,
    name: "The Champagne Grandeur",
    slug: "the-champagne-grandeur",
    categorySlug: "bouquets",
    description: "Highlights the luxurious tone and abundant size of the bouquet.",
    priceMinor: 77500,
    sku: "FLR-0020",
    mainImage: "/assets/img/x20.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 21,
    name: "Passion Royale",
    slug: "passion-royale",
    categorySlug: "bouquets",
    description: "Hand-tied in our Dubai atelier from the morning’s freshest stems.",
    priceMinor: 197500,
    sku: "FLR-0021",
    mainImage: "/assets/img/x21.webp",
    isFeatured: true,
    tag: "Grand format",
  },
  {
    legacyId: 22,
    name: "Whimsical White",
    slug: "whimsical-white",
    categorySlug: "bouquets",
    description: "Captures the fresh, lighthearted feel of the arrangement.",
    priceMinor: 24500,
    sku: "FLR-0022",
    mainImage: "/assets/img/x22.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 23,
    name: "Sweet Pink Serenity",
    slug: "sweet-pink-serenity",
    categorySlug: "bouquets",
    description: "Reflects the calming and elegant mood of this specific bouquet.",
    priceMinor: 19500,
    sku: "FLR-0023",
    mainImage: "/assets/img/x23.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 24,
    name: "Midnight Mist",
    slug: "midnight-mist",
    categorySlug: "bouquets",
    description: "Captures the deep purple tones paired with the sophisticated grey wrapping.",
    priceMinor: 19500,
    sku: "FLR-0024",
    mainImage: "/assets/img/x24.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 25,
    name: "The Florinsta Noir",
    slug: "the-florinsta-noir",
    categorySlug: "bouquets",
    description: "Highlights the bold contrast between the delicate blooms and the black wrapping.",
    priceMinor: 14500,
    sku: "FLR-0025",
    mainImage: "/assets/img/x25.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 26,
    name: "Serene Meadow",
    slug: "serene-meadow",
    categorySlug: "bouquets",
    description: "Captures the soft, calming combination of white and green tones.",
    priceMinor: 57500,
    sku: "FLR-0026",
    mainImage: "/assets/img/x26.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 27,
    name: "Florinsta Blush",
    slug: "florinsta-blush",
    categorySlug: "bouquets",
    description: "Hand-tied in our Dubai atelier from the morning’s freshest stems.",
    priceMinor: 14500,
    sku: "FLR-0027",
    mainImage: "/assets/img/x27.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 28,
    name: "Violet Grace",
    slug: "violet-grace",
    categorySlug: "bouquets",
    description: "Highlights the elegant orchids that serve as a focal point in this arrangement.",
    priceMinor: 47500,
    sku: "FLR-0028",
    mainImage: "/assets/img/x28.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 29,
    name: "Orchid Symphony",
    slug: "orchid-symphony",
    categorySlug: "bouquets",
    description: "Captures the harmonious blend of the purple orchid blooms and their delicate stems.",
    priceMinor: 19500,
    sku: "FLR-0029",
    mainImage: "/assets/img/x29.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 30,
    name: "Whimsical Lavender",
    slug: "whimsical-lavender",
    categorySlug: "bouquets",
    description: "Captures the playful yet elegant aesthetic of the arrangement.",
    priceMinor: 47500,
    sku: "FLR-0030",
    mainImage: "/assets/img/x30.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 31,
    name: "Botanical Serenity",
    slug: "botanical-serenity",
    categorySlug: "bouquets",
    description: "Emphasizes the calming, organic feel of the arrangement.",
    priceMinor: 47500,
    sku: "FLR-0031",
    mainImage: "/assets/img/x31.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 32,
    name: "The Ethereal Dusk",
    slug: "the-ethereal-dusk",
    categorySlug: "bouquets",
    description: "Evokes the refined beauty of soft pastel blooms fading into the deep, mysterious wrap.",
    priceMinor: 37500,
    sku: "FLR-0032",
    mainImage: "/assets/img/x32.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 33,
    name: "The Sapphire Cloud",
    slug: "the-sapphire-cloud",
    categorySlug: "bouquets",
    description: "Highlights the soft, billowy texture of the wrapping contrasted with the vibrant, jewel-toned blooms.",
    priceMinor: 357500,
    sku: "FLR-0033",
    mainImage: "/assets/img/x33.webp",
    isFeatured: true,
    tag: "Grand format",
  },
  {
    legacyId: 34,
    name: "The Royal Amethyst",
    slug: "the-royal-amethyst",
    categorySlug: "bouquets",
    description: "Highlights the regal, deep purple color.",
    priceMinor: 37500,
    sku: "FLR-0034",
    mainImage: "/assets/img/x34.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 35,
    name: "Dubai Twilight",
    slug: "dubai-twilight",
    categorySlug: "bouquets",
    description: "This name draws inspiration from the rich, deep hues of an evening in the desert. It represents deep, lasting bonds and is an excellent choice for anniversaries or romantic gestures.",
    priceMinor: 37500,
    sku: "FLR-0035",
    mainImage: "/assets/img/x35.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 36,
    name: "The Cotton Cloud",
    slug: "the-cotton-cloud",
    categorySlug: "bouquets",
    description: "Focuses on the fluffy, cloud-like texture of the blooms.",
    priceMinor: 37500,
    sku: "FLR-0036",
    mainImage: "/assets/img/x36.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 37,
    name: "The Verdant Oasis",
    slug: "the-verdant-oasis",
    categorySlug: "bouquets",
    description: "Evokes a feeling of lush freshness, perfect for your base in the UAE.",
    priceMinor: 27500,
    sku: "FLR-0037",
    mainImage: "/assets/img/x37.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 38,
    name: "Florinsta Prism",
    slug: "florinsta-prism",
    categorySlug: "bouquets",
    description: "Hand-tied in our Dubai atelier from the morning’s freshest stems.",
    priceMinor: 37500,
    sku: "FLR-0038",
    mainImage: "/assets/img/x38.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 39,
    name: "Florinsta Monochromatic",
    slug: "florinsta-monochromatic",
    categorySlug: "bouquets",
    description: "Hand-tied in our Dubai atelier from the morning’s freshest stems.",
    priceMinor: 37500,
    sku: "FLR-0039",
    mainImage: "/assets/img/x39.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 40,
    name: "The Sterling Serenity",
    slug: "the-sterling-serenity",
    categorySlug: "bouquets",
    description: "Emphasizes the high-quality silver/grey tones and the calm, monochromatic theme.",
    priceMinor: 37500,
    sku: "FLR-0040",
    mainImage: "/assets/img/x40.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 41,
    name: "Garnet Muse",
    slug: "garnet-muse",
    categorySlug: "bouquets",
    description: "Some moments require more than just words. Speak volumes with the deep, passionate hues of our Garnet Muse.",
    priceMinor: 37500,
    sku: "FLR-0041",
    mainImage: "/assets/img/x41.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 42,
    name: "Rosalind's Garden",
    slug: "rosalinds-garden",
    categorySlug: "baskets",
    description: "Understated luxury. The perfect blend of rustic charm and refined beauty.",
    priceMinor: 89500,
    sku: "FLR-0042",
    mainImage: "/assets/img/x42.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 43,
    name: "Château Rosé",
    slug: "ch-teau-ros",
    categorySlug: "baskets",
    description: "Effortless elegance in every petal. A symphony of velvet garden roses, curated for the refined soul. 🌸.",
    priceMinor: 79500,
    sku: "FLR-0043",
    mainImage: "/assets/img/x43.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 44,
    name: "Opulent Blue Wicker",
    slug: "opulent-blue-wicker",
    categorySlug: "baskets",
    description: "Understated luxury. The timeless beauty of blue and white, woven into a masterpiece.",
    priceMinor: 89500,
    sku: "FLR-0044",
    mainImage: "/assets/img/x44.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 45,
    name: "The Côte d'Azur White",
    slug: "the-c-te-dazur-white",
    categorySlug: "baskets",
    description: "Serenity and grace, woven into a masterpiece. Elevate your space with this timeless arrangement.",
    priceMinor: 89500,
    sku: "FLR-0045",
    mainImage: "/assets/img/x45.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 46,
    name: "Infinite Passion Couture",
    slug: "infinite-passion-couture",
    categorySlug: "baskets",
    description: "Not just an arrangement, but a declaration. Elevate your space with the timeless luxury of pure red roses.",
    priceMinor: 79500,
    sku: "FLR-0046",
    mainImage: "/assets/img/x46.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 47,
    name: "Ethereal Blush",
    slug: "ethereal-blush",
    categorySlug: "baskets",
    description: "Highlights the delicate interplay between the blue hydrangeas and the blush pink lisianthus, suggesting a graceful and sophisticated dreamscape.",
    priceMinor: 79500,
    sku: "FLR-0047",
    mainImage: "/assets/img/x47.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 48,
    name: "The Pristine Sphere",
    slug: "the-pristine-sphere",
    categorySlug: "baskets",
    description: "Highlights the architectural perfection and flawless, rounded form of the arrangement, conveying a sense of modern, structured luxury.",
    priceMinor: 79500,
    sku: "FLR-0048",
    mainImage: "/assets/img/x48.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 49,
    name: "Blush Serenity",
    slug: "blush-serenity",
    categorySlug: "baskets",
    description: "Captures the gentle, calming union of soft pinks and whites, suggesting an atmosphere of peace and refined elegance.",
    priceMinor: 79500,
    sku: "FLR-0049",
    mainImage: "/assets/img/x49.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 50,
    name: "Summer Solstice",
    slug: "summer-solstice",
    categorySlug: "baskets",
    description: "Perfectly describes the vibrant, high-energy color palette, implying a peak moment of beauty and life.",
    priceMinor: 69500,
    sku: "FLR-0050",
    mainImage: "/assets/img/x50.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 51,
    name: "The Ethereal Sphere",
    slug: "the-ethereal-sphere",
    categorySlug: "baskets",
    description: "Focuses on the perfect, rounded architectural shape of the arrangement, conveying a sense of modern, structured luxury.",
    priceMinor: 79500,
    sku: "FLR-0051",
    mainImage: "/assets/img/x51.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 52,
    name: "The Opulent Sphere",
    slug: "the-opulent-sphere",
    categorySlug: "baskets",
    description: "Highlights the dense, rounded architecture of the arrangement, conveying a sense of fullness, abundance, and high-end design precision.",
    priceMinor: 187500,
    sku: "FLR-0052",
    mainImage: "/assets/img/x52.webp",
    isFeatured: true,
    tag: "Grand format",
  },
  {
    legacyId: 53,
    name: "Atelier Elegance",
    slug: "atelier-elegance",
    categorySlug: "baskets",
    description: "Highlights the sophistication of the blue palette, implying a refined, curated experience that transcends standard floral design.",
    priceMinor: 47500,
    sku: "FLR-0053",
    mainImage: "/assets/img/x53.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 54,
    name: "Enchanted Garden Basket",
    slug: "enchanted-garden-basket",
    categorySlug: "baskets",
    description: "Evokes the feeling of walking through a hidden, fairytale-like garden, suggesting an arrangement that is both whimsical and meticulously curated.",
    priceMinor: 57500,
    sku: "FLR-0054",
    mainImage: "/assets/img/x54.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 55,
    name: "Amethyst Solstice",
    slug: "amethyst-solstice",
    categorySlug: "baskets",
    description: "Combines the regal, deep purple tones of \"amethyst\" with the solar energy of the sunflowers, suggesting a powerful and transformative union.",
    priceMinor: 77500,
    sku: "FLR-0055",
    mainImage: "/assets/img/x55.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 56,
    name: "Blush Serenade",
    slug: "blush-serenade",
    categorySlug: "baskets",
    description: "Captures the gentle, harmonious blend of soft pink and rose tones, evoking the romantic atmosphere of a curated garden.",
    priceMinor: 57500,
    sku: "FLR-0056",
    mainImage: "/assets/img/x56.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 57,
    name: "Blush Botanica",
    slug: "blush-botanica",
    categorySlug: "baskets",
    description: "Captures the sophisticated, organic elegance of the varied pink blooms, suggesting a curated garden brought indoors.",
    priceMinor: 47500,
    sku: "FLR-0057",
    mainImage: "/assets/img/x57.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 58,
    name: "Azure Sunburst",
    slug: "azure-sunburst",
    categorySlug: "baskets",
    description: "Captures the striking contrast between the intense, radiant yellow blooms and the cool, calming blue tones, suggesting a moment of vibrant energy and refined balance.",
    priceMinor: 47500,
    sku: "FLR-0058",
    mainImage: "/assets/img/x58.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 59,
    name: "Morning Dew Garden",
    slug: "morning-dew-garden",
    categorySlug: "baskets",
    description: "Evokes the freshness and purity of a quiet, sunlit garden, ideal for clients looking for a restorative and elegant floral display.",
    priceMinor: 37500,
    sku: "FLR-0059",
    mainImage: "/assets/img/x59.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 60,
    name: "Celestial Majesty",
    slug: "celestial-majesty",
    categorySlug: "baskets",
    description: "Evokes a sense of elevated, ethereal beauty, perfect for high-stakes presentations where you want to emphasize artistic excellence.",
    priceMinor: 129500,
    sku: "FLR-0060",
    mainImage: "/assets/img/x60.webp",
    isFeatured: true,
    tag: "Grand format",
  },
  {
    legacyId: 61,
    name: "Imperial Blossom Tower",
    slug: "imperial-blossom-tower",
    categorySlug: "baskets",
    description: "Emphasizes the bold, authoritative presence of the arrangement, ideal for luxury brands looking to make a strong visual statement.",
    priceMinor: 199500,
    sku: "FLR-0061",
    mainImage: "/assets/img/x61.webp",
    isFeatured: true,
    tag: "Grand format",
  },
  {
    legacyId: 62,
    name: "The Sovereign Ascent",
    slug: "the-sovereign-ascent",
    categorySlug: "baskets",
    description: "Highlights the vertical, towering structure of the arrangement, positioning it as an authoritative and grand masterpiece for exclusive settings.",
    priceMinor: 199500,
    sku: "FLR-0062",
    mainImage: "/assets/img/x62.webp",
    isFeatured: true,
    tag: "Grand format",
  },
  {
    legacyId: 63,
    name: "Serene Grandeur",
    slug: "serene-grandeur",
    categorySlug: "baskets",
    description: "Captures the balance between the lush, full volume of the flowers and the calming presence of the greenery.",
    priceMinor: 67500,
    sku: "FLR-0063",
    mainImage: "/assets/img/x63.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 64,
    name: "Varrance Atelier",
    slug: "varrance-atelier",
    categorySlug: "baskets",
    description: "Composed and finished by hand in our Dubai atelier.",
    priceMinor: 67500,
    sku: "FLR-0064",
    mainImage: "/assets/img/x64.webp",
    isFeatured: false,
    tag: "",
  },
  {
    legacyId: 65,
    name: "Vargees Atelier",
    slug: "vargees-atelier",
    categorySlug: "baskets",
    description: "Composed and finished by hand in our Dubai atelier.",
    priceMinor: 67500,
    sku: "FLR-0065",
    mainImage: "/assets/img/x65.webp",
    isFeatured: false,
    tag: "",
  },
];
